/* Generated by Proofly React Export */
import * as React from "react";

export interface CountUpProps {
  targetNumber?: number;
  durationS?: number;
  fontFamily?: string;
  color?: string;
  fontSizePx?: number;
  lineHeightPx?: number;
  fontWeight?: "Thin" | "Extra Light" | "Light" | "Regular" | "Medium" | "Semi Bold" | "Bold" | "Extra Bold" | "Black";
}

declare const CountUp: React.ComponentType<CountUpProps>;
export default CountUp;
