/* Generated by Proofly React Export */
import * as React from "react";

export interface PrimaryProps {
  variant?: "Main" | "With Border";
  buttonText?: string;
  link?: string;
}

declare const Primary: React.ComponentType<PrimaryProps>;
export default Primary;
