/* Generated by Proofly React Export */
import * as React from "react";

export interface TestimonialsProps {
  variant?: "Main" | "Selected" | "Selected Colored";
  click?: (...args: any[]) => void;
  image?: string | { src: string; srcSet?: string; alt?: string };
}

declare const Testimonials: React.ComponentType<TestimonialsProps>;
export default Testimonials;
