import type { PortfolioRecord, ReviewRecord } from "@/types/portfolio";

const now = "2026-04-28T00:00:00.000Z";

export const samplePortfolios: PortfolioRecord[] = [
  {
    id: "clifton-terrace-recovery",
    title: "Clifton Terrace End of Tenancy Recovery",
    slug: "clifton-terrace-recovery",
    description:
      "A high-traffic rental property that had fallen significantly below hygiene standards. The project required a multi-stage reset including professional dust extraction, deep steam cleaning of all hard surfaces, and intensive appliance detailing. Our team focused on restoring the original finish to ensure a successful inventory sign-off for the landlord.",
    coverImage: {
      url: "/images/after.png",
      alt: "Clifton Terrace kitchen restoration",
      kind: "cover",
    },
    galleryImages: [
      {
        url: "/images/before.png",
        alt: "Heavy grease accumulation on kitchen surfaces before cleaning",
        kind: "before",
      },
      {
        url: "/images/after.png",
        alt: "Fully sanitized and polished kitchen after intensive recovery",
        kind: "after",
      },
      {
        url: "/images/story-transformation.png",
        alt: "Detailed extraction in living areas",
        kind: "detail",
      },
    ],
    serviceType: "End Of Tenancy Cleaning",
    location: "Bristol",
    completionDate: "2026-04-12T00:00:00.000Z",
    turnaroundTime: "14 hours",
    resultSummary: "Property restored to inventory-ready condition, deposit released in full.",
    metrics: [
      { label: "Hygiene Pass", value: "100%" },
      { label: "Rooms Reset", value: "6 Spaces" },
      { label: "Turnaround", value: "Single Day" },
    ],
    featured: true,
    createdAt: now,
    propertyType: "3-Bed Apartment",
    propertySize: "950 sq ft",
    clientIssue: "Accumulated grime and failed internal inspection.",
    challenge: "Heavy grease in kitchen and limescale in bathrooms requiring industrial-grade agents.",
    teamSize: "3 Specialists",
    tasksCompleted: [
      "Full kitchen degrease and appliance detailing",
      "Bathroom descaling and steam sanitization",
      "High-level dust extraction",
      "Window and frame restorative cleaning",
      "Hard floor scrub and polish",
    ],
    handoverNotes: "Inventory clerk confirmed 'as-new' condition for all high-touch areas.",
    trustBadges: ["Deposit Safe", "Inventory Ready", "DBS Checked"],
    resultBadge: "Inventory Ready",
  },
  {
    id: "somerset-logistics-deep-clean",
    title: "Somerset Logistics Unit Deep Clean",
    slug: "somerset-logistics-deep-clean",
    description:
      "A large-scale commercial logistics unit requiring a comprehensive deep clean following a lease end. The focus was on industrial floor restoration, high-level structural dusting, and sanitization of staff welfare facilities to meet corporate handover requirements.",
    coverImage: {
      url: "/images/after2.png",
      alt: "Warehouse floor restoration",
      kind: "cover",
    },
    galleryImages: [
      {
        url: "/images/before2.png",
        alt: "Stained industrial floor before deep cleaning",
        kind: "before",
      },
      {
        url: "/images/after2.png",
        alt: "Polished and restored warehouse floor",
        kind: "after",
      },
    ],
    serviceType: "Commercial Cleaning",
    location: "Taunton, Somerset",
    completionDate: "2026-03-28T00:00:00.000Z",
    turnaroundTime: "48 hours",
    resultSummary: "Full unit restoration compliant with commercial lease exit standards.",
    metrics: [
      { label: "Floor Area", value: "12,000 sq ft" },
      { label: "Team Size", value: "6 Staff" },
      { label: "Complaints", value: "Zero" },
    ],
    featured: true,
    createdAt: now,
    propertyType: "Industrial Unit",
    propertySize: "12,000 sq ft",
    clientIssue: "Lease exit requirements for pristine floor and structural condition.",
    challenge: "Removing stubborn forklift tire marks and industrial oil residues.",
    teamSize: "6 Staff",
    tasksCompleted: [
      "Industrial floor scrubbing and degreasing",
      "High-level beam and duct dusting",
      "Welfare block deep clean",
      "External loading bay pressure wash",
    ],
    handoverNotes: "Facility manager signed off without any remedial actions needed.",
    trustBadges: ["Fully Insured", "Agency Standard", "Health & Safety Verified"],
    resultBadge: "Lease Compliant",
  },
  {
    id: "riverside-letting-handover",
    title: "Riverside Letting Apartment Handover",
    slug: "riverside-letting-handover",
    description:
      "A fast-track handover for a Riverside property manager. The apartment needed a crisp, professional reset between tenancies within a tight 24-hour window to maintain booking momentum.",
    coverImage: {
      url: "/images/gallery-hero.png",
      alt: "Riverside apartment living area",
      kind: "cover",
    },
    galleryImages: [
      {
        url: "/images/before.png",
        alt: "Living area before cleaning",
        kind: "before",
      },
      {
        url: "/images/after.png",
        alt: "Living area after professional reset",
        kind: "after",
      },
    ],
    serviceType: "End Of Tenancy Cleaning",
    location: "Bristol",
    completionDate: "2026-04-05T00:00:00.000Z",
    turnaroundTime: "8 hours",
    resultSummary: "Rapid turnaround achieved with zero impact on new tenant move-in date.",
    metrics: [
      { label: "Window", value: "24h Ready" },
      { label: "Quality", value: "Premium" },
      { label: "Satisfaction", value: "100%" },
    ],
    featured: false,
    createdAt: now,
    propertyType: "2-Bed Apartment",
    propertySize: "750 sq ft",
    clientIssue: "Short gap between tenancies requiring urgent professional reset.",
    challenge: "Coordinating multiple cleaning zones simultaneously to meet the deadline.",
    teamSize: "2 Specialists",
    tasksCompleted: [
      "Rapid-response deep clean",
      "Internal window polishing",
      "Carpet refresh",
      "Sanitization pass",
    ],
    handoverNotes: "Keys returned to agency 4 hours ahead of schedule.",
    trustBadges: ["24h Turnaround", "DBS Checked", "Deposit Safe"],
    resultBadge: "Tenant Ready",
  },
  {
    id: "redland-family-restoration",
    title: "Redland Family Home Restoration",
    slug: "redland-family-restoration",
    description:
      "A comprehensive restoration of a large Victorian family home in Redland. This project focused on delicate surface care for heritage features while delivering a modern standard of hygiene across all living areas.",
    coverImage: {
      url: "/images/about-hero.png",
      alt: "Redland home hallway finish",
      kind: "cover",
    },
    galleryImages: [
      {
        url: "/images/before2.png",
        alt: "Heritage hallway before restoration",
        kind: "before",
      },
      {
        url: "/images/after2.png",
        alt: "Heritage hallway after restorative clean",
        kind: "after",
      },
    ],
    serviceType: "Deep Cleaning",
    location: "Redland, Bristol",
    completionDate: "2026-03-15T00:00:00.000Z",
    turnaroundTime: "22 hours",
    resultSummary: "Heritage features protected and restored to a vibrant, clean state.",
    metrics: [
      { label: "Heritage Care", value: "Certified" },
      { label: "Total Hours", value: "22h" },
      { label: "Status", value: "Restored" },
    ],
    featured: false,
    createdAt: now,
    propertyType: "5-Bed Victorian House",
    propertySize: "2,400 sq ft",
    clientIssue: "General build-up over years and delicate original features needing care.",
    challenge: "Cleaning intricate plasterwork and original tiled flooring without damage.",
    teamSize: "4 Specialists",
    tasksCompleted: [
      "Heritage floor restoration",
      "Plasterwork dust removal",
      "Full property deep reset",
      "Sanitization of all touchpoints",
    ],
    handoverNotes: "Client delighted with the preservation of original features.",
    trustBadges: ["Fully Insured", "Agency Standard", "Handover Verified"],
    resultBadge: "Heritage Restored",
  },
  {
    id: "merchant-yard-office-reset",
    title: "Merchant Yard Office Reset",
    slug: "merchant-yard-office-reset",
    description:
      "A strategic office reset for a tech firm moving into the Merchant Yard complex. The clean was designed to create a sterile, welcoming environment for a 40-person team.",
    coverImage: {
      url: "/images/hero-bg-new.png",
      alt: "Office reception area",
      kind: "cover",
    },
    galleryImages: [
      {
        url: "/images/before.png",
        alt: "Office space before move-in clean",
        kind: "before",
      },
      {
        url: "/images/after.png",
        alt: "Sanitized office environment",
        kind: "after",
      },
    ],
    serviceType: "Commercial Cleaning",
    location: "Bristol",
    completionDate: "2026-02-20T00:00:00.000Z",
    turnaroundTime: "12 hours",
    resultSummary: "Workplace sanitized and ready for immediate hardware deployment.",
    metrics: [
      { label: "Desks Ready", value: "40" },
      { label: "Air Quality", value: "Improved" },
      { label: "Access", value: "Weekend" },
    ],
    featured: false,
    createdAt: now,
    propertyType: "Modern Office",
    propertySize: "3,500 sq ft",
    clientIssue: "Dust and minor debris from previous occupants.",
    challenge: "Meeting strict IT hygiene standards for server and desk areas.",
    teamSize: "3 Specialists",
    tasksCompleted: [
      "IT equipment surface sanitization",
      "Kitchenette deep clean",
      "Glass partition polishing",
      "Carpet steam extraction",
    ],
    handoverNotes: "Ready for IT setup teams on Monday morning.",
    trustBadges: ["Fully Insured", "DBS Checked", "Agency Standard"],
    resultBadge: "Office Ready",
  },
  {
    id: "kingsdown-builder-dust-clearance",
    title: "Kingsdown Builder Dust Clearance",
    slug: "kingsdown-builder-dust-clearance",
    description:
      "Post-renovation dust clearance for a newly finished basement conversion. This project required industrial-strength HEPA filtration to eliminate fine plaster dust from every crevice.",
    coverImage: {
      url: "/images/team-stats.png",
      alt: "Basement conversion finish",
      kind: "cover",
    },
    galleryImages: [
      {
        url: "/images/before2.png",
        alt: "Plaster dust build-up",
        kind: "before",
      },
      {
        url: "/images/after2.png",
        alt: "Dust-free basement reveal",
        kind: "after",
      },
    ],
    serviceType: "After Builders Cleaning",
    location: "Kingsdown, Bristol",
    completionDate: "2026-04-20T00:00:00.000Z",
    turnaroundTime: "10 hours",
    resultSummary: "Fine dust eliminated, property ready for furniture installation.",
    metrics: [
      { label: "Dust Extraction", value: "HEPA" },
      { label: "Safety", value: "Passed" },
      { label: "Ready", value: "Instant" },
    ],
    featured: true,
    createdAt: now,
    propertyType: "Basement Conversion",
    propertySize: "600 sq ft",
    clientIssue: "Micro-fine plaster dust covering all new surfaces.",
    challenge: "Ensuring air quality was restored alongside surface cleanliness.",
    teamSize: "2 Specialists",
    tasksCompleted: [
      "HEPA vacuum extraction",
      "Tack-cloth fine dusting",
      "Floor scrubbing",
      "Air scrub pass",
    ],
    handoverNotes: "Basement is now 100% dust-free and safe for occupation.",
    trustBadges: ["Handover Verified", "DBS Checked", "Fully Insured"],
    resultBadge: "Snag-Free",
  },
];

export const sampleReviews: ReviewRecord[] = [
  {
    id: "review-clifton",
    portfolioId: "clifton-terrace-recovery",
    landlordName: "Sarah Thompson",
    company: "Thompson Residential",
    rating: 5,
    comment:
      "The property was in a shocking state. Joseph & Co didn't just clean it; they restored it. The inventory clerk was amazed at the transformation. Deposit released without issue.",
    approved: true,
    createdAt: now,
    portfolioTitle: "Clifton Terrace End of Tenancy Recovery",
    portfolioSlug: "clifton-terrace-recovery",
  },
  {
    id: "review-somerset",
    portfolioId: "somerset-logistics-deep-clean",
    landlordName: "Mark Evans",
    company: "Evans Logistics Hub",
    rating: 5,
    comment:
      "A massive undertaking. The floor looks better than when we first moved in. Professional, punctual, and met all our lease exit criteria.",
    approved: true,
    createdAt: now,
    portfolioTitle: "Somerset Logistics Unit Deep Clean",
    portfolioSlug: "somerset-logistics-deep-clean",
  },
  {
    id: "review-riverside",
    portfolioId: "riverside-letting-handover",
    landlordName: "David Knight",
    company: "Knight Property Management",
    rating: 5,
    comment:
      "We needed a 24h turnaround to avoid losing a booking. Joseph & Co delivered a spotless apartment with hours to spare. Unbelievable speed and quality.",
    approved: true,
    createdAt: now,
    portfolioTitle: "Riverside Letting Apartment Handover",
    portfolioSlug: "riverside-letting-handover",
  },
  {
    id: "review-redland",
    portfolioId: "redland-family-restoration",
    landlordName: "Emily Watson",
    company: "Private Homeowner",
    rating: 5,
    comment:
      "I was worried about the original tiles, but the team handled them with such care. The house feels brand new but retains its character. Highly recommended.",
    approved: true,
    createdAt: now,
    portfolioTitle: "Redland Family Home Restoration",
    portfolioSlug: "redland-family-restoration",
  },
];
